return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "css",
        "scss",
        "html",
        "tsx",
        "typescript",
        "javascript",
        "graphql",
        "prisma",
        "dockerfile",
        "bash",
        "lua",
        "json",
        "json5",
        "yaml",
        "markdown",
        "markdown_inline",
        "regex",
        "gitcommit",
        "gitignore",
        "diff",
        "dart",
        "python",
        "toml",
        "ninja",
        "rst",
      },
    },
  },
}
